version: "3.8"
services:
  db:
    image: mongo
    container_name: interview-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=interview
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/entrypoint.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge