kind: Service
apiVersion: v1
metadata:
  name:  analyzer-dna-service
  namespace: interview-meli
  labels:
    app: analyzer-dna
    tier: backend
    owner: interview
spec:
  selector:
    app: analyzer-dna
  ports:
    - name:  grpc
      port:  50051
      targetPort: 50051
  type: LoadBalancer